<%flags>
inherit => undef
</%flags>
<%args>
$org => 'SAR11'
$novel => 0
$absent => 0
$default => 0
$pathogen => 1
$debug => 0
$relative => 0
$absolute => 1
</%args>
<%init>
#
# absolute generates integer counts of COG category members
# relative generates relative proporitions of # COGs in a category vs total number of COGs in the genome
#
use lib '/home/sgivan/projects/COGDB/lib';
use COGDB;
my ($cogdb,$localcogs);
my ($time00,$time01,$time02,$time03,$time04,$time05);
if ($debug) {
  open(LOG,">cog_content.log") or die "can't open cog_content.log: $!";
  $time00 = time();
  print LOG "time00: $time00\n";
}

$cogdb = COGDB->new();
$localcogs = $cogdb->localcogs();

my $whogdb = $cogdb->whog();
my $categories = $cogdb->category()->fetch_all();
my $organism = $localcogs->organism({Code => $org});

#
# this next line is a little hairy ...
# use the MMG organism's COG division to fetch
# a list of public organisms in the same COG division
#
my $organisms = $cogdb->organism()->fetch_by_division($organism->division()->name(),$pathogen);## non-local organisms in this COG division

my $localwhogdb = $localcogs->whog();
my $whogs;

my $content_dir = $m->current_comp()->source_dir();
$content_dir .= '/content';

my $content_file = "$content_dir/$org" . ".html";

unlink($content_file) if ($debug);

my $content_relative = "content/$org" . ".html";
my $novel_link = "<a href=\"?org=$org\">present</a> - <a href=\"?org=$org;novel=1\">novel</a> - <a href=\"?org=$org;absent=1\">absent</a>";
my $novel_link_style = "\"background-color: rgb(200,200,200); padding: 2px;\"";
my $base_link = "?org=$org";

if ($novel) {

  $content_file = "$content_dir/$org" . "_novel.html";
  unlink($content_file) if ($debug);
  $content_relative = "content/$org" . "_novel.html";
  $novel_link =~ s/>novel</><span style=$novel_link_style>novel<\/span></;
  $base_link .= ";novel=1";

  if (!-e $content_file) {

    $whogs = $localwhogdb->fetch_by_organism($organism);
    my @novel_whogs;
    foreach my $whog (@$whogs) {
      push(@novel_whogs,$whog) if ($whog->novel());
    }
    $whogs = \@novel_whogs;
  }

} elsif ($absent) {

  $content_file = "$content_dir/$org" . "_absent.html";
  unlink($content_file) if ($debug);
  $content_relative = "content/$org" . "_absent.html";
  $novel_link =~ s/>absent</><span style=$novel_link_style>absent<\/span></;
  $base_link .= ";absent=1";
  $whogs = $localwhogdb->fetch_absent_cogs($organism) unless (-e $content_file);

} else {

  $whogs = $localwhogdb->fetch_by_organism($organism) unless (-e $content_file);
  $novel_link =~ s/>present</><span style=$novel_link_style>present<\/span></;

} ## end of if $novel or $absent or default

if ($debug) {
  $time01 = time() - $time00;
  print LOG "time01:  $time01\n";
}

my %category_db = ();
#
#	Structure of %category_db
#
#	$category_db{"category name"} = ( COGDB::Whog, ...)
#

my $factfinder_url = "/cgi-bin/factfinder.cgi?qry_type=displayOrf;org=" . $organism->id_local() . ";orf_name=";
my $cog_url = "http://www.ncbi.nlm.nih.gov/Structure/cdd/cddsrv.cgi?uid=";
#my $cog_url = "http://www.ncbi.nlm.nih.gov/COG/new/release/cow.cgi?cog=";
#my $cog_url = "http://www.ncbi.nlm.nih.gov/COG/grace/wiew.cgi?";

my $data_file = $content_file;
my $data_relative = $content_relative;
$data_file =~ s/\.html/\.txt/;
$data_relative =~ s/\.html/.txt/;
unlink($content_file,$data_file) if ($debug);
my $tally_whog_category = 0;
#
# If content file doesn't already exist, create new one
#
if (!-e $content_file) {

  foreach my $whog (@$whogs) {
    my $cog = $absent ? $whog : $whog->cog();
    my $categories = $cog->categories();
    foreach my $category (@$categories) {
        ++$tally_whog_category;
        push(@{$category_db{$category->name()}},$whog);
    }
  }

  if ($debug) {
    $time02 = time() - $time00;
    print LOG "time02:  $time02\n";
  }

  my ($image_MAP,$top_Y,$bot_Y,$spacing)  = ("<map name=\"colorkey\">",0,17.28,17.28);
  open(OUT,">$content_file") or die "can't open content file: $!";
  open(DATA,">$data_file") or die "can't open '$data_file': $!";
  my $cnt = 0;
  my %coverage;
  foreach my $category (@$categories) {
    last if ($debug && ++$cnt == 5);
    my $tally = $category_db{$category->name()} ? scalar(@{$category_db{$category->name()}}) : 0;
    my $relative_amt = $tally_whog_category ?  sprintf("%2.2f", ($tally/$tally_whog_category)*100) : 'zero';
    print OUT "<a name=\"" . $category->name() . "\"></a><h4>" . $category->name() . " - ($tally, $relative_amt \%)</h4>";

    $image_MAP .= "<area href=\"#" . $category->name() . "\" shape=\"rect\" coords=\"0,$top_Y,400,$bot_Y\" alt=\"\" />\n";
    $top_Y = $bot_Y;
    $bot_Y += $spacing;

    #
    # if this category has members, generate output
    #
    if ($tally) {
      print OUT "<div style=\"padding-left: 10px;\"><table style=\"width: 800px; background-color: silver;\">\n";
      print OUT "<tr><th>ORF</th><th>COG</th><th>N</th><th>COG Description</th></tr>\n";

      my $whog_cnt = 0;
      foreach my $whog (sort { $a->name() cmp $b->name() } @{$category_db{$category->name()}}) {
        last if ($debug && ++$whog_cnt == 11);
        my $li;

        if (!$absent && $whog->novel()) {
            $li = "<tr style=\"background-color: red;\"><td>";
        } else {
            $li = "<tr style=\"background-color: white;\"><td>";
        }

        my $whogname = $absent ? '-' : $whog->name();
        my $cogname = $absent ? $whog->name() : $whog->cog()->name();
        my $cogdesc = $absent ? $whog->description : $whog->cog()->description();

        my $coverage;
        if ($coverage{$cogname}) {
            $coverage = $coverage{$cogname};
        } else {

            $coverage = $m->scomp('.divCOGs', whogdb => $whogdb, cog => $absent ? $whog : $whog->cog(), organism => $organism, cnt => scalar(@$organisms), pathogen => $pathogen);
            $coverage{$cogname} = $coverage;
        }

        $coverage =~ s/[\015\012\r\n]//g;
        $li .= $absent ? '-</td>' : "<a href=\"$factfinder_url" . "$whogname\">$whogname</a></td>";

        $li .= "<td><a href=\"$cog_url" . $cogname . "\" target=\"_NCBI_COG\">$cogname</a></td><td>" . "<a href=\"divCOGs.html?cog=";
        $absent ?  $li .= $whog->id() :  $li .= $whog->cog->id();
        $li .= ";division=" . $organism->division()->id() . "\">$coverage</a></td><td>$cogdesc</td></tr>\n";

        print OUT $li;

        print DATA "$whogname\t$cogname\t$coverage\t$cogdesc\t" . $category->name() . "\n";

      } ## end of foreach my $whog

      print OUT "</table></div>\n";

      if ($debug) {
        $time03 = time() - $time00;
        print LOG "time03:  $time03\n";
      }
    } ## end of if ($tally)
  } ## end of foreach my $category


  if ($debug) {
    $time04 = time() - $time00;
    print LOG "time04:  $time04\n";
  }

  $image_MAP .= "</map>\n";
  print OUT $image_MAP;
  close(OUT);
  close(DATA);
  
} ## end of if (!-e $content_file) ##

if ($debug) {
  $time05 = time() - $time00;
  print LOG "time05:  $time05\n";
}

close(LOG);
</%init>
<%def .divCOGs>
<%args>
$cog
$organism
$cnt
$whogdb
$pathogen => 0
</%args>
<%init>
my $string;
my $coverage = $whogdb->coverage_by_division({ cog => $cog, division => $organism->division(), pathogen => $pathogen });
#my $coverage = [1, 2, 3];

if ($coverage && scalar(@$coverage)) {
  $string .= scalar(@$coverage) . "/$cnt";
} else {
  $string .= "0/$cnt";

}
#$string .= "</a>";

# #   foreach my $organism (sort { $a->code() cmp $b->code() } @$organisms) {
# #     my $whogs = $whogdb->fetch_by_whog({ cog => $cog, organism => $organism });
# #     if (scalar(@$whogs)) {
# #       $string .= $organism->code() . " ";
# #     } else {
# #       $string .= " &ndash; &nbsp;";
# #     }

#   }

</%init>
<% $string %>
</%def>

